- name: create a google cloud compute engine instance
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
#    gcp_project: "ansible-collections"
     gcp_cred_kind: "serviceaccount"
#    gcp_cred_file: "google.json" 


  tasks:
  - name: create a disk
    google.cloud.gcp_compute_disk:
      name: disk-instance
      size_gb: 50
      source_image: projects/centos-cloud/global/images/centos-7-v20200618
      zone: us-central1-a
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
#      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: disk

  - name: create a network
    google.cloud.gcp_compute_network:
      name: network-instance
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
#      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: network

  - name: create a address
    google.cloud.gcp_compute_address:
      name: address-instance
      region: us-central1
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
#      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: address

  - name: create a firewall
    google.cloud.gcp_compute_firewall:
      name: allow-ssh
      network: "{{ network }}"
      allowed:
      - ip_protocol: tcp
        ports:
        - '22'
      target_tags:
      - dev
      source_ranges:
      - 0.0.0.0/0
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
#      service_account_file: "{{ gcp_cred_file }}"
      state: present

  - name: create a instance
    google.cloud.gcp_compute_instance:
      name: test-vm
      machine_type: n1-standard-1
      disks:
      - auto_delete: 'true'
        boot: 'true'
        source: "{{ disk }}"
      - auto_delete: 'true'
        interface: NVME
        type: SCRATCH
        initialize_params:
          disk_type: local-ssd
      labels:
        environment: dev
      tags:
        items:
        - dev
      network_interfaces:
      - network: "{{ network }}"
        access_configs:
        - name: External NAT
          nat_ip: "{{ address }}"
          type: ONE_TO_ONE_NAT
      zone: us-central1-a
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
#      service_account_file: "{{ gcp_cred_file }}"
      service_accounts:
      - email:  638796027664-compute@developer.gserviceaccount.com
        scopes:
        - https://www.googleapis.com/auth/monitoring.write
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/service.management.readonly
        - https://www.googleapis.com/auth/servicecontrol
      state: present
